packages:
  - "config"
  - "packages/*"
catalogs:
  samchon:
    nestia: &nestia ^12.0.0-rc.4
    "@nestia/benchmark": *nestia
    "@nestia/core": *nestia
    "@nestia/fetcher": *nestia
    "@nestia/e2e": *nestia
    "@nestia/editor": *nestia
    "@nestia/migrate": *nestia
    "@nestia/sdk": *nestia
    tstl: ^3.0.0
    typia: ^13.0.0
  utils:
    uuid: ^13.0.0
    rimraf: ^6.1.3
  typescript:
    ttsc: &ttsc ^0.18.2
    "@ttsc/unplugin": *ttsc
    "@ttsc/paths": *ttsc
    "@ttsc/lint": *ttsc
    typescript: ^7.0.2
